import jsPDF from 'jspdf';

export interface ReportData {
  title: string;
  subtitle?: string;
  data: any[];
  columns: string[];
  summary?: Record<string, string | number>;
  companyInfo?: {
    name: string;
    address: string;
    email: string;
  };
}

export const generatePDFReport = async (reportData: ReportData): Promise<void> => {
  const pdf = new jsPDF();
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  let currentY = 20;

  // Company Header
  if (reportData.companyInfo) {
    pdf.setFontSize(16);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(37, 99, 235);
    pdf.text(reportData.companyInfo.name, 20, currentY);
    currentY += 8;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(100, 100, 100);
    pdf.text(reportData.companyInfo.address, 20, currentY);
    currentY += 6;
    pdf.text(reportData.companyInfo.email, 20, currentY);
    currentY += 15;
  }

  // Report Title
  pdf.setFontSize(18);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(0, 0, 0);
  pdf.text(reportData.title, 20, currentY);
  currentY += 12;

  // Subtitle
  if (reportData.subtitle) {
    pdf.setFontSize(12);
    pdf.setFont('helvetica', 'normal');
    pdf.setTextColor(80, 80, 80);
    pdf.text(reportData.subtitle, 20, currentY);
    currentY += 10;
  }

  // Generation Date
  pdf.setFontSize(10);
  pdf.setTextColor(100, 100, 100);
  pdf.text(`Generated on: ${new Date().toLocaleDateString()} at ${new Date().toLocaleTimeString()}`, 20, currentY);
  currentY += 15;

  // Summary Section
  if (reportData.summary && Object.keys(reportData.summary).length > 0) {
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'bold');
    pdf.setTextColor(0, 0, 0);
    pdf.text('Summary', 20, currentY);
    currentY += 10;

    pdf.setFontSize(10);
    pdf.setFont('helvetica', 'normal');
    
    let summaryX = 20;
    let summaryY = currentY;
    
    Object.entries(reportData.summary).forEach(([key, value]) => {
      pdf.setFont('helvetica', 'bold');
      pdf.text(`${key}:`, summaryX, summaryY);
      pdf.setFont('helvetica', 'normal');
      pdf.text(String(value), summaryX + 25, summaryY);
      
      summaryX += 60;
      if (summaryX > pageWidth - 60) {
        summaryX = 20;
        summaryY += 8;
      }
    });
    
    currentY += 35;
  }
  
  // Table Header
  const colWidth = (pageWidth - 40) / reportData.columns.length;
  
  pdf.setFillColor(37, 99, 235);
  pdf.rect(20, currentY, pageWidth - 40, 10, 'F');
  
  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  
  reportData.columns.forEach((column, index) => {
    const x = 20 + (index * colWidth) + 2;
    pdf.text(column, x, currentY + 7);
  });
  
  currentY += 12;
  
  // Table Data
  pdf.setTextColor(0, 0, 0);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(9);
  
  reportData.data.forEach((row, rowIndex) => {
    if (currentY > pageHeight - 30) {
      // Add new page
      pdf.addPage();
      currentY = 20;
      
      // Re-add table header
      pdf.setFillColor(37, 99, 235);
      pdf.rect(20, currentY, pageWidth - 40, 10, 'F');
      
      pdf.setTextColor(255, 255, 255);
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'bold');
      
      reportData.columns.forEach((column, index) => {
        const x = 20 + (index * colWidth) + 2;
        pdf.text(column, x, currentY + 7);
      });
      
      currentY += 12;
      pdf.setTextColor(0, 0, 0);
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(9);
    }
    
    // Alternate row colors
    if (rowIndex % 2 === 0) {
      pdf.setFillColor(249, 250, 251);
      pdf.rect(20, currentY - 2, pageWidth - 40, 10, 'F');
    }
    
    reportData.columns.forEach((column, colIndex) => {
      const x = 20 + (colIndex * colWidth) + 2;
      const cellValue = String(row[column] || '').substring(0, 25);
      pdf.text(cellValue, x, currentY + 5);
    });
    
    currentY += 10;
  });
  
  // Footer
  const totalPages = pdf.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    pdf.setPage(i);
    pdf.setFontSize(8);
    pdf.setTextColor(150, 150, 150);
    pdf.text(`Page ${i} of ${totalPages}`, pageWidth - 30, pageHeight - 10);
    pdf.text('Generated by StockMaster', 20, pageHeight - 10);
  }
  
  // Download the PDF
  const filename = `${reportData.title.replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
  pdf.save(filename);
};

// Specific report generators
export const generateMovementHistoryReport = async (movements: any[], filters?: any) => {
  const reportData: ReportData = {
    title: 'Stock Movement History Report',
    subtitle: `Comprehensive audit trail of inventory movements${filters ? ' (Filtered)' : ''}`,
    data: movements.map(movement => ({
      'Date': movement.timestamp?.toDate?.() ? 
        movement.timestamp.toDate().toLocaleDateString() : 
        new Date(movement.timestamp).toLocaleDateString(),
      'Type': movement.type,
      'Product': movement.product_name,
      'SKU': movement.sku,
      'Quantity': movement.quantity > 0 ? `+${movement.quantity}` : movement.quantity,
      'From': movement.from_location || '-',
      'To': movement.to_location || '-',
      'User': movement.user_name,
      'Reference': movement.reference
    })),
    columns: ['Date', 'Type', 'Product', 'SKU', 'Quantity', 'From', 'To', 'User', 'Reference'],
    summary: {
      'Total Movements': movements.length,
      'Receipts': movements.filter(m => m.type === 'receipt').length,
      'Deliveries': movements.filter(m => m.type === 'delivery').length,
      'Transfers': movements.filter(m => m.type === 'transfer').length,
      'Adjustments': movements.filter(m => m.type === 'adjustment').length,
      'Users Involved': new Set(movements.map(m => m.user_name)).size
    },
    companyInfo: {
      name: 'StockMaster Inventory System',
      address: 'Warehouse Management Suite',
      email: 'reports@stockmaster.com'
    }
  };
  
  await generatePDFReport(reportData);
};

export const generateProductReport = async (products: any[]) => {
  const reportData: ReportData = {
    title: 'Product Inventory Report',
    subtitle: 'Complete product catalog with stock levels and pricing',
    data: products.map(product => ({
      'Product Name': product.name,
      'SKU': product.sku,
      'Category': product.category,
      'Stock': product.stock,
      'Unit': product.unit,
      'Cost Price': `$${product.cost_price?.toFixed(2) || '0.00'}`,
      'Selling Price': `$${product.selling_price?.toFixed(2) || '0.00'}`,
      'Supplier': product.supplier,
      'Status': product.status
    })),
    columns: ['Product Name', 'SKU', 'Category', 'Stock', 'Unit', 'Cost Price', 'Selling Price', 'Supplier', 'Status'],
    summary: {
      'Total Products': products.length,
      'In Stock': products.filter(p => p.stock > 0).length,
      'Out of Stock': products.filter(p => p.stock === 0).length,
      'Low Stock': products.filter(p => p.stock <= p.reorder_level && p.stock > 0).length,
      'Categories': new Set(products.map(p => p.category)).size,
      'Total Value': `$${products.reduce((sum, p) => sum + (p.stock * p.cost_price || 0), 0).toFixed(2)}`
    },
    companyInfo: {
      name: 'StockMaster Inventory System',
      address: 'Product Catalog Report',
      email: 'reports@stockmaster.com'
    }
  };
  
  await generatePDFReport(reportData);
};

export const generateOperationsReport = async (operations: any[], type: string) => {
  const reportData: ReportData = {
    title: `${type.charAt(0).toUpperCase() + type.slice(1)} Operations Report`,
    subtitle: `Detailed ${type} operations analysis`,
    data: operations.map(op => {
      const baseData = {
        'ID': op[`${type}_id`] || op.id,
        'Status': op.status,
        'Created': op.created_at?.toDate?.() ? 
          op.created_at.toDate().toLocaleDateString() : 
          new Date(op.created_at).toLocaleDateString()
      };
      
      if (type === 'receipt') {
        return {
          ...baseData,
          'Supplier': op.supplier,
          'Items': op.total_items,
          'Value': `$${op.total_value?.toFixed(2) || '0.00'}`,
          'Notes': op.notes || '-'
        };
      } else if (type === 'delivery') {
        return {
          ...baseData,
          'Customer': op.customer,
          'Product': op.product_name,
          'Quantity': op.quantity,
          'Destination': op.to_location,
          'Notes': op.notes || '-'
        };
      } else if (type === 'transfer') {
        return {
          ...baseData,
          'Product': op.product_name,
          'From': op.from_location,
          'To': op.to_location,
          'Quantity': op.quantity,
          'Notes': op.notes || '-'
        };
      } else {
        return {
          ...baseData,
          'Product': op.product_name,
          'Quantity': op.quantity > 0 ? `+${op.quantity}` : op.quantity,
          'Reason': op.reason,
          'Location': op.location,
          'Notes': op.notes || '-'
        };
      }
    }),
    columns: type === 'receipt' ? 
      ['ID', 'Supplier', 'Items', 'Value', 'Status', 'Created', 'Notes'] :
      type === 'delivery' ?
      ['ID', 'Customer', 'Product', 'Quantity', 'Destination', 'Status', 'Created', 'Notes'] :
      type === 'transfer' ?
      ['ID', 'Product', 'From', 'To', 'Quantity', 'Status', 'Created', 'Notes'] :
      ['ID', 'Product', 'Quantity', 'Reason', 'Location', 'Status', 'Created', 'Notes'],
    summary: {
      [`Total ${type.charAt(0).toUpperCase() + type.slice(1)}s`]: operations.length,
      'Pending': operations.filter(op => op.status === 'pending').length,
      'Completed': operations.filter(op => op.status === 'completed').length,
      'This Month': operations.filter(op => {
        const opDate = op.created_at?.toDate?.() ? op.created_at.toDate() : new Date(op.created_at);
        const now = new Date();
        return opDate.getMonth() === now.getMonth() && opDate.getFullYear() === now.getFullYear();
      }).length
    },
    companyInfo: {
      name: 'StockMaster Inventory System',
      address: `${type.charAt(0).toUpperCase() + type.slice(1)} Operations Analysis`,
      email: 'reports@stockmaster.com'
    }
  };
  
  await generatePDFReport(reportData);
};